/*
 * Resolves a (bottle, motor, prop) selection to an actual 3dFiles/ STL path.
 *
 * Fan enclosures follow (or will follow, once the parametric generator exists) the naming
 * convention: FanEnclosure_<bottle>_M<motorDiameter>_P<propDiameter>.stl, e.g.
 * FanEnclosure_05L_M8-5_P55.stl for an 8.5mm motor. Decimals become hyphens. We compute that
 * expected filename and check it against knownFiles (generated by deployConfiguratorAssets.ps1
 * from an actual scan of 3dFiles/, see stl-manifest.json) before falling back to
 * VARIANT_DATA.legacyOverrides for today's pre-convention files. 0.75L has no enclosures of its
 * own yet, so it borrows from 0.5L (preferred) or 1L.
 */

const BOTTLE_FOLDER = {
  "05L": "05l_Bottle",
  "075L": "075l_Bottle",
  "1L": "1l_Bottle",
};

const BOTTLE_FALLBACK_ORDER = {
  "075L": ["05L", "1L"],
};

function formatDiameterToken(diameterMm) {
  return String(diameterMm).replace(".", "-");
}

function formatPropToken(propId) {
  // propId is already e.g. "55mm" -> token "P55"
  return "P" + propId.replace("mm", "");
}

function expectedFanFilePath(bottleId, motorDiameterMm, propId) {
  const folder = BOTTLE_FOLDER[bottleId];
  if (!folder) return null;
  const motorToken = "M" + formatDiameterToken(motorDiameterMm);
  const propToken = formatPropToken(propId);
  return `3dFiles/${folder}/FanEnclosure_${bottleId}_${motorToken}_${propToken}.stl`;
}

function legacyFanFilePath(data, bottleId, motorDiameterMm, propId) {
  return data.legacyOverrides?.[bottleId]?.[motorDiameterMm]?.[propId] ?? null;
}

function tryBottle(data, knownFiles, bottleId, motorDiameterMm, propId) {
  const expected = expectedFanFilePath(bottleId, motorDiameterMm, propId);
  if (expected && knownFiles.has(expected)) return expected;
  return legacyFanFilePath(data, bottleId, motorDiameterMm, propId);
}

/** Resolves the fan enclosure/holder STL for a (bottle, motor, prop) combo, or null if none exists yet. */
export function resolveFanFile(data, knownFiles, bottleId, motorId, propId) {
  const motor = data.motors[motorId];
  if (!motor) return null;

  const direct = tryBottle(data, knownFiles, bottleId, motor.diameterMm, propId);
  if (direct) return direct;

  for (const fallbackBottle of BOTTLE_FALLBACK_ORDER[bottleId] ?? []) {
    const viaFallback = tryBottle(data, knownFiles, fallbackBottle, motor.diameterMm, propId);
    if (viaFallback) return viaFallback;
  }

  return null;
}

/** Resolves the bottle's centerpiece/bridge connector STL - always available, not motor/prop-dependent. */
export function resolveConnectorFile(data, bottleId) {
  return data.bottles[bottleId]?.connectorFile ?? null;
}

/** Every prop id valid for motorId that also resolves to a real fan file for bottleId. */
export function availablePropsFor(data, knownFiles, bottleId, motorId) {
  const motor = data.motors[motorId];
  if (!motor) return [];
  return motor.validProps.filter((propId) => resolveFanFile(data, knownFiles, bottleId, motorId, propId) !== null);
}

/** Every motor id that has at least one available prop for bottleId. */
export function availableMotorsFor(data, knownFiles, bottleId) {
  return Object.keys(data.motors).filter(
    (motorId) => availablePropsFor(data, knownFiles, bottleId, motorId).length > 0
  );
}
