"""
Encodes a Vite-built frontend (dist/ folder) into two Arduino headers:
- website_content.h:   PROGMEM byte arrays, one per file
- website_functions.h: setupServerFunctions(), registering a server.on() route
                        per file that serves its byte array via send_P()

Ported from Duck-main/firmware/duck_frontend/encodeInArduino.py, generalized
to take the dist folder as an argument instead of assuming it lives next to
this script.

Usage: python tools/encodeInArduino.py [dist_folder_path]
       (defaults to minikenterprise_frontend/dist relative to the repo root)
"""

import os
import sys


### Binary Buffer Encoding ###
def padded_hex(i, l):
    given_int = i
    given_len = l

    hex_result = hex(given_int)[2:]  # remove '0x' from beginning of str
    num_hex_chars = len(hex_result)
    extra_zeros = '0' * (given_len - num_hex_chars)  # may not get used..

    return ('0x' + hex_result if num_hex_chars == given_len else
            '?' * given_len if num_hex_chars > given_len else
            '0x' + extra_zeros + hex_result if num_hex_chars < given_len else
            None)


def to_byte_array_string(content_string):
    byte_string = ""
    length = len(content_string)
    bytes_per_line = 20

    for index, char in enumerate(content_string):
        char_code = ord(char)
        if char_code > 127:
            char_code = 0x00

        if index < length - 1:
            byte_string += f"{padded_hex(char_code,2)},"
        else:
            byte_string += f"{padded_hex(char_code,2)}"

        if index != 0 and (index + 1) % bytes_per_line == 0:
            byte_string += "\n"
    return byte_string


def file_to_progmem_array_string(file_path: str, filename: str, artifact_name: str = None):
    arduino_string = ""
    with open(file_path, 'r', encoding='utf-8', errors='replace') as file:
        content = file.read()

        array_length = len(content)
        encoded_content = to_byte_array_string(content)

        print(f"Encoding {filename} with {array_length} characters")
        arduino_string += f"//File: {filename}\n"
        if artifact_name is None:
            artifact_name = get_artifact_name(filename)

        arduino_string += f"const uint16_t {artifact_name}_length = {array_length};\n"
        arduino_string += f"const char {artifact_name}[] PROGMEM = {{ \n{encoded_content} }};\n"

    return arduino_string, array_length


### Functional Encoding ###
def get_arduino_server_function(foldername: str, filename: str, custom_path: str = None, artifact_name: str = None):
    if artifact_name is None:
        artifact_name = get_artifact_name(filename)

    path = filename
    if foldername is not None:
        path = "/" + foldername + "/" + filename

    if custom_path is not None:
        path = custom_path

    return f"server.on(\"{path}\", handle_{artifact_name});\n"


def get_arduino_content_callback(filename: str, artifact_name: str = None):
    mime_type = get_mime_string(filename)
    if artifact_name is None:
        artifact_name = get_artifact_name(filename)

    return f"void handle_{artifact_name}() {{ server.send_P(200, \"{mime_type}\", {artifact_name},{artifact_name}_length);}}\n"


### File Creation ###
def create_functions_file(dist_folder_path):
    server_functions = ""
    content_callbacks = ""

    # Index
    server_functions += get_arduino_server_function(None, 'index.html', "/")
    content_callbacks += get_arduino_content_callback('index.html')

    # Settings
    folder_name = 'settings'
    filename = 'index.html'
    server_functions += get_arduino_server_function(folder_name, filename, "/settings/", 'settings_index')
    content_callbacks += get_arduino_content_callback(filename, 'settings_index')

    # Assets
    folder_name = 'assets'
    assets_path = os.path.join(dist_folder_path, folder_name)
    asset_filenames = [f for f in os.listdir(assets_path) if os.path.isfile(os.path.join(assets_path, f))]

    for filename in asset_filenames:
        server_functions += get_arduino_server_function(folder_name, filename)
        content_callbacks += get_arduino_content_callback(filename)

    file_path = os.path.join(dist_folder_path, 'website_functions.h')
    file_definition = "WEBSITE_FUNCTIONS_H"

    with open(file_path, 'w') as file:
        file.write("/* This file has been generated by tools/encodeInArduino.py */\n")
        file.write("/* The callbacks send encoded content found in website_content.h */\n")
        file.write(f"#ifndef {file_definition}\n")
        file.write(f"#define {file_definition}\n\n")
        file.write("#include \"Arduino.h\"\n\n")
        file.write("#include \"website_content.h\"\n\n")
        file.write("// content callbacks\n")
        file.write(content_callbacks)
        file.write("\n")
        file.write("void setupServerFunctions() {\n")
        file.write(server_functions)
        file.write("}\n\n")
        file.write("#endif\n")


def create_content_file(dist_folder_path):
    content = ""
    total_bytes = 0
    file_count = 0

    # Index
    filename = 'index.html'
    file_path = os.path.join(dist_folder_path, filename)
    file_content, array_length = file_to_progmem_array_string(file_path, filename)
    content += file_content
    total_bytes += array_length
    file_count += 1

    # Settings
    folder_name = 'settings'
    filename = 'index.html'
    file_path = os.path.join(dist_folder_path, folder_name, filename)
    file_content, array_length = file_to_progmem_array_string(file_path, filename, 'settings_index')
    content += file_content
    total_bytes += array_length
    file_count += 1

    # Assets
    folder_name = 'assets'
    assets_path = os.path.join(dist_folder_path, folder_name)
    asset_filenames = [f for f in os.listdir(assets_path) if os.path.isfile(os.path.join(assets_path, f))]

    for filename in asset_filenames:
        file_path = os.path.join(assets_path, filename)
        file_content, array_length = file_to_progmem_array_string(file_path, filename)
        content += file_content
        total_bytes += array_length
        file_count += 1

    file_path = os.path.join(dist_folder_path, 'website_content.h')
    file_definition = "WEBSITE_CONTENT_H"

    with open(file_path, 'w') as file:
        file.write("/* This file has been generated by tools/encodeInArduino.py */\n")
        file.write("/* It contains the website's content encoded as byte arrays for flash memory */\n")
        file.write(f"#ifndef {file_definition}\n")
        file.write(f"#define {file_definition}\n\n")
        file.write("#include \"Arduino.h\"\n\n")
        file.write(content)
        file.write("\n")
        file.write("#endif\n")

    print(f"Total embedded size: {total_bytes} bytes across {file_count} files")


### HELPER FUNCTIONS ###
def get_artifact_name(file_name: str):
    file_name_parts = file_name.split(".")
    artifact_name = file_name_parts[0] + "_" + file_name_parts[1]
    if "-" in artifact_name:
        artifact_name = artifact_name.replace("-", "_")
    return artifact_name


def get_mime_string(file_name):
    file_extension = os.path.splitext(file_name)[1]
    if file_extension == '.html':
        return "text/html"
    elif file_extension == '.css':
        return "text/css"
    elif file_extension == '.js':
        return "application/javascript"
    return 'text/plain'


def main():
    if len(sys.argv) > 1:
        dist_folder_path = os.path.abspath(sys.argv[1])
    else:
        repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        dist_folder_path = os.path.join(repo_root, 'minikenterprise_frontend', 'dist')

    print(f"Encoding frontend from: {dist_folder_path}")
    create_content_file(dist_folder_path)
    create_functions_file(dist_folder_path)


if __name__ == "__main__":
    main()
