#ifndef FRONTEND_SERVER_H
#define FRONTEND_SERVER_H

#include <ESP8266WebServer.h>
#include <string.h>
#include "Settings.h"

#define DEBUG_FRONTEND_SERVER

bool serverOnline = false;

ESP8266WebServer server(80);

// Generated by tools/encodeInArduino.py from the minikenterprise_frontend/
// build output - see deployFrontend.ps1. Declares setupServerFunctions(),
// which registers a server.on() route for every embedded Control UI asset.
// Must come after `server` is declared above, since it references it.
#include "website_functions.h"

//Function Prototypes
void FrontendServer_init();
void FrontendServer_update();
void FrontendServer_start();
void FrontendServer_stop();
void handleSettingsGet();
void handleSettingsSave();

void FrontendServer_init(){
  setupServerFunctions();

  server.on("/api/settings", HTTP_GET, handleSettingsGet);
  server.on("/api/settings/save", HTTP_POST, handleSettingsSave);

  server.onNotFound([]() {
    server.send(404, "text/plain", "404: Not Found");
  });

  FrontendServer_start();
}

void FrontendServer_update(){
  server.handleClient();
}

void FrontendServer_start(){
  server.begin();
  serverOnline = true;
}

void FrontendServer_stop(){
  server.stop();
  serverOnline = false;
}

/*** SETTINGS API (plain key=value lines in, form-urlencoded fields out) ***/
void handleSettingsGet(){
  String response = "";
  response += "apMode=" + String(settings.apMode ? 1 : 0) + "\n";
  response += "apSsid=" + String(settings.apSsid) + "\n";
  response += "apPassword=" + String(settings.apPassword) + "\n";
  response += "staSsid=" + String(settings.staSsid) + "\n";
  response += "staPassword=" + String(settings.staPassword) + "\n";
  response += "motorEn=" + String(settings.motorEn) + "\n";
  response += "motorIn1=" + String(settings.motorIn1) + "\n";
  response += "motorIn2=" + String(settings.motorIn2) + "\n";
  response += "motorIn3=" + String(settings.motorIn3) + "\n";
  response += "motorIn4=" + String(settings.motorIn4) + "\n";
  response += "ledCount=" + String(settings.ledCount) + "\n";
  response += "regularPwmLimitPercent=" + String(settings.regularPwmLimitPercent) + "\n";
  response += "boostPwmLimitPercent=" + String(settings.boostPwmLimitPercent) + "\n";
  server.send(200, "text/plain", response);
}

void handleSettingsSave(){
  if(server.hasArg("apMode")) settings.apMode = server.arg("apMode").toInt() != 0;
  if(server.hasArg("apSsid")) strncpy(settings.apSsid, server.arg("apSsid").c_str(), SSID_MAX_LEN - 1);
  if(server.hasArg("apPassword")) strncpy(settings.apPassword, server.arg("apPassword").c_str(), PASSWORD_MAX_LEN - 1);
  if(server.hasArg("staSsid")) strncpy(settings.staSsid, server.arg("staSsid").c_str(), SSID_MAX_LEN - 1);
  if(server.hasArg("staPassword")) strncpy(settings.staPassword, server.arg("staPassword").c_str(), PASSWORD_MAX_LEN - 1);
  if(server.hasArg("motorEn")) settings.motorEn = server.arg("motorEn").toInt();
  if(server.hasArg("motorIn1")) settings.motorIn1 = server.arg("motorIn1").toInt();
  if(server.hasArg("motorIn2")) settings.motorIn2 = server.arg("motorIn2").toInt();
  if(server.hasArg("motorIn3")) settings.motorIn3 = server.arg("motorIn3").toInt();
  if(server.hasArg("motorIn4")) settings.motorIn4 = server.arg("motorIn4").toInt();
  if(server.hasArg("ledCount")) settings.ledCount = server.arg("ledCount").toInt();
  if(server.hasArg("regularPwmLimitPercent")) settings.regularPwmLimitPercent = server.arg("regularPwmLimitPercent").toInt();
  if(server.hasArg("boostPwmLimitPercent")) settings.boostPwmLimitPercent = server.arg("boostPwmLimitPercent").toInt();

  Settings_save();

  server.send(200, "text/plain", "Settings saved, restarting...");
  delay(500);
  ESP.restart();
}
#endif
