/* This file has been generated by tools/encodeInArduino.py */
/* The callbacks send encoded content found in website_content.h */
#ifndef WEBSITE_FUNCTIONS_H
#define WEBSITE_FUNCTIONS_H

#include "Arduino.h"

#include "website_content.h"

// content callbacks
void handle_index_html() { server.send_P(200, "text/html", index_html,index_html_length);}
void handle_settings_index() { server.send_P(200, "text/html", settings_index,settings_index_length);}
void handle_favicon_BrpTr_E7_ico() { server.send_P(200, "text/plain", favicon_BrpTr_E7_ico,favicon_BrpTr_E7_ico_length);}
void handle_main_Bfuj9TKD_js() { server.send_P(200, "application/javascript", main_Bfuj9TKD_js,main_Bfuj9TKD_js_length);}
void handle_main_C9oq52Dn_css() { server.send_P(200, "text/css", main_C9oq52Dn_css,main_C9oq52Dn_css_length);}
void handle_modulepreload_polyfill_B5Qt9EMX_js() { server.send_P(200, "application/javascript", modulepreload_polyfill_B5Qt9EMX_js,modulepreload_polyfill_B5Qt9EMX_js_length);}
void handle_settings_BmJ9NouM_css() { server.send_P(200, "text/css", settings_BmJ9NouM_css,settings_BmJ9NouM_css_length);}
void handle_settings_C5xNdXOE_js() { server.send_P(200, "application/javascript", settings_C5xNdXOE_js,settings_C5xNdXOE_js_length);}

void setupServerFunctions() {
server.on("/", handle_index_html);
server.on("/settings/", handle_settings_index);
server.on("/assets/favicon-BrpTr-E7.ico", handle_favicon_BrpTr_E7_ico);
server.on("/assets/main-Bfuj9TKD.js", handle_main_Bfuj9TKD_js);
server.on("/assets/main-C9oq52Dn.css", handle_main_C9oq52Dn_css);
server.on("/assets/modulepreload-polyfill-B5Qt9EMX.js", handle_modulepreload_polyfill_B5Qt9EMX_js);
server.on("/assets/settings-BmJ9NouM.css", handle_settings_BmJ9NouM_css);
server.on("/assets/settings-C5xNdXOE.js", handle_settings_C5xNdXOE_js);
}

#endif
